name: Publish MCP Server

on:
  push:
    branches: [main]
    paths: ['packages/mcp/**']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build MCP server
        run: bun run build:mcp
        
      - name: Setup NPM registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
        
      - name: Publish to NPM
        run: cd packages/mcp && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
